# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PageHelp.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PageHelp(object):
    def setupUi(self, PageHelp):
        PageHelp.setObjectName("PageHelp")
        PageHelp.resize(429, 301)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        PageHelp.setPalette(palette)
        self.TitreFilm = QtWidgets.QLineEdit(PageHelp)
        self.TitreFilm.setGeometry(QtCore.QRect(30, 50, 311, 21))
        self.TitreFilm.setObjectName("TitreFilm")
        self.QuestionID = QtWidgets.QLabel(PageHelp)
        self.QuestionID.setGeometry(QtCore.QRect(30, 20, 291, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.QuestionID.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.QuestionID.setFont(font)
        self.QuestionID.setObjectName("QuestionID")
        self.TableFilmsCorrespondants = QTableWidget2(PageHelp)
        self.TableFilmsCorrespondants.setGeometry(QtCore.QRect(30, 80, 371, 191))
        self.TableFilmsCorrespondants.setShowGrid(False)
        self.TableFilmsCorrespondants.setCornerButtonEnabled(False)
        self.TableFilmsCorrespondants.setRowCount(10)
        self.TableFilmsCorrespondants.setColumnCount(1)
        self.TableFilmsCorrespondants.setObjectName("TableFilmsCorrespondants")
        self.TableFilmsCorrespondants.horizontalHeader().setVisible(False)
        self.TableFilmsCorrespondants.horizontalHeader().setDefaultSectionSize(271)
        self.TableFilmsCorrespondants.verticalHeader().setVisible(False)
        self.TableFilmsCorrespondants.verticalHeader().setDefaultSectionSize(20)
        self.Help = QtWidgets.QLabel(PageHelp)
        self.Help.setGeometry(QtCore.QRect(270, 225, 151, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(234, 144, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 144, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Help.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.Help.setFont(font)
        self.Help.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Help.setObjectName("Help")
        self.OK = QtWidgets.QPushButton(PageHelp)
        self.OK.setGeometry(QtCore.QRect(347, 45, 61, 32))
        self.OK.setObjectName("OK")

        self.retranslateUi(PageHelp)
        QtCore.QMetaObject.connectSlotsByName(PageHelp)

    def retranslateUi(self, PageHelp):
        _translate = QtCore.QCoreApplication.translate
        PageHelp.setWindowTitle(_translate("PageHelp", "Form"))
        self.QuestionID.setText(_translate("PageHelp", "Enter the title of the movie :"))
        self.Help.setText(_translate("PageHelp", "HELP"))
        self.OK.setText(_translate("PageHelp", "OK"))

from QTableWidget2 import QTableWidget2
