# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PageRechercheFilms.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PageRechercheFilms(object):
    def setupUi(self, PageRechercheFilms):
        PageRechercheFilms.setObjectName("PageRechercheFilms")
        PageRechercheFilms.resize(800, 500)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        PageRechercheFilms.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial Hebrew")
        font.setPointSize(14)
        PageRechercheFilms.setFont(font)
        self.Action = QtWidgets.QCheckBox(PageRechercheFilms)
        self.Action.setGeometry(QtCore.QRect(50, 310, 101, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Action.setPalette(palette)
        self.Action.setObjectName("Action")
        self.Adventure = QtWidgets.QCheckBox(PageRechercheFilms)
        self.Adventure.setGeometry(QtCore.QRect(50, 350, 101, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Adventure.setPalette(palette)
        self.Adventure.setObjectName("Adventure")
        self.Comedy = QtWidgets.QCheckBox(PageRechercheFilms)
        self.Comedy.setGeometry(QtCore.QRect(50, 330, 121, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Comedy.setPalette(palette)
        self.Comedy.setObjectName("Comedy")
        self.QuestionID = QtWidgets.QLabel(PageRechercheFilms)
        self.QuestionID.setGeometry(QtCore.QRect(40, 115, 291, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.QuestionID.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.QuestionID.setFont(font)
        self.QuestionID.setObjectName("QuestionID")
        self.QuestionGenres = QtWidgets.QLabel(PageRechercheFilms)
        self.QuestionGenres.setGeometry(QtCore.QRect(40, 290, 341, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 239, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.QuestionGenres.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.QuestionGenres.setFont(font)
        self.QuestionGenres.setObjectName("QuestionGenres")
        self.SearchButton = QtWidgets.QPushButton(PageRechercheFilms)
        self.SearchButton.setGeometry(QtCore.QRect(40, 390, 113, 32))
        self.SearchButton.setObjectName("SearchButton")
        self.ReturnButton = QtWidgets.QPushButton(PageRechercheFilms)
        self.ReturnButton.setGeometry(QtCore.QRect(40, 420, 113, 32))
        self.ReturnButton.setObjectName("ReturnButton")
        self.TitreFilmCourant = QtWidgets.QLabel(PageRechercheFilms)
        self.TitreFilmCourant.setGeometry(QtCore.QRect(410, 470, 371, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 246, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 246, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.TitreFilmCourant.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.TitreFilmCourant.setFont(font)
        self.TitreFilmCourant.setText("")
        self.TitreFilmCourant.setAlignment(QtCore.Qt.AlignCenter)
        self.TitreFilmCourant.setObjectName("TitreFilmCourant")
        self.AfficheFilmCourant = QtWidgets.QLabel(PageRechercheFilms)
        self.AfficheFilmCourant.setEnabled(True)
        self.AfficheFilmCourant.setGeometry(QtCore.QRect(470, 90, 251, 371))
        self.AfficheFilmCourant.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AfficheFilmCourant.setText("")
        self.AfficheFilmCourant.setScaledContents(True)
        self.AfficheFilmCourant.setObjectName("AfficheFilmCourant")
        self.TitreLabel = QtWidgets.QLabel(PageRechercheFilms)
        self.TitreLabel.setGeometry(QtCore.QRect(0, -10, 781, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(234, 144, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 144, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.TitreLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.TitreLabel.setFont(font)
        self.TitreLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TitreLabel.setObjectName("TitreLabel")
        self.ReponseID = QtWidgets.QLineEdit(PageRechercheFilms)
        self.ReponseID.setGeometry(QtCore.QRect(40, 140, 271, 21))
        self.ReponseID.setObjectName("ReponseID")
        self.TableFilmsCorrespondants = QTableWidget2(PageRechercheFilms)
        self.TableFilmsCorrespondants.setGeometry(QtCore.QRect(40, 170, 271, 111))
        self.TableFilmsCorrespondants.setShowGrid(False)
        self.TableFilmsCorrespondants.setCornerButtonEnabled(False)
        self.TableFilmsCorrespondants.setRowCount(10)
        self.TableFilmsCorrespondants.setColumnCount(1)
        self.TableFilmsCorrespondants.setObjectName("TableFilmsCorrespondants")
        self.TableFilmsCorrespondants.horizontalHeader().setVisible(False)
        self.TableFilmsCorrespondants.horizontalHeader().setDefaultSectionSize(271)
        self.TableFilmsCorrespondants.verticalHeader().setVisible(False)
        self.TableFilmsCorrespondants.verticalHeader().setDefaultSectionSize(20)
        self.CadreFilmCourant = QLabel2(PageRechercheFilms)
        self.CadreFilmCourant.setEnabled(False)
        self.CadreFilmCourant.setGeometry(QtCore.QRect(470, 90, 251, 371))
        self.CadreFilmCourant.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CadreFilmCourant.setText("")
        self.CadreFilmCourant.setScaledContents(True)
        self.CadreFilmCourant.setObjectName("CadreFilmCourant")

        self.retranslateUi(PageRechercheFilms)
        QtCore.QMetaObject.connectSlotsByName(PageRechercheFilms)

    def retranslateUi(self, PageRechercheFilms):
        _translate = QtCore.QCoreApplication.translate
        PageRechercheFilms.setWindowTitle(_translate("PageRechercheFilms", "Form"))
        self.Action.setText(_translate("PageRechercheFilms", "Action"))
        self.Adventure.setText(_translate("PageRechercheFilms", "Comedy"))
        self.Comedy.setText(_translate("PageRechercheFilms", "Adventure"))
        self.QuestionID.setText(_translate("PageRechercheFilms", "Enter the title of a movie you liked"))
        self.QuestionGenres.setText(_translate("PageRechercheFilms", "Which kind of movie do you want to see ?"))
        self.SearchButton.setText(_translate("PageRechercheFilms", "Search"))
        self.ReturnButton.setText(_translate("PageRechercheFilms", "Return"))
        self.TitreLabel.setText(_translate("PageRechercheFilms", "MOVIE RECOMMENDATION"))

from QLabel2 import QLabel2
from QTableWidget2 import QTableWidget2
