# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PageKevinBacon.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PageKevinBacon(object):
    def setupUi(self, PageKevinBacon):
        PageKevinBacon.setObjectName("PageKevinBacon")
        PageKevinBacon.resize(779, 489)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        PageKevinBacon.setPalette(palette)
        self.Collection = QtWidgets.QLabel(PageKevinBacon)
        self.Collection.setGeometry(QtCore.QRect(-20, -10, 801, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(234, 144, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 144, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Collection.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.Collection.setFont(font)
        self.Collection.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Collection.setObjectName("Collection")
        self.TitreFilm1 = QtWidgets.QLineEdit(PageKevinBacon)
        self.TitreFilm1.setGeometry(QtCore.QRect(30, 120, 611, 21))
        self.TitreFilm1.setObjectName("TitreFilm1")
        self.TitreFilm2 = QtWidgets.QLineEdit(PageKevinBacon)
        self.TitreFilm2.setGeometry(QtCore.QRect(30, 150, 611, 21))
        self.TitreFilm2.setObjectName("TitreFilm2")
        self.AfficheFilm2 = QtWidgets.QLabel(PageKevinBacon)
        self.AfficheFilm2.setGeometry(QtCore.QRect(470, 230, 161, 221))
        self.AfficheFilm2.setText("")
        self.AfficheFilm2.setScaledContents(True)
        self.AfficheFilm2.setObjectName("AfficheFilm2")
        self.JolisPoints = QtWidgets.QLabel(PageKevinBacon)
        self.JolisPoints.setGeometry(QtCore.QRect(340, 230, 91, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.JolisPoints.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(130)
        self.JolisPoints.setFont(font)
        self.JolisPoints.setObjectName("JolisPoints")
        self.Browse1 = QtWidgets.QPushButton(PageKevinBacon)
        self.Browse1.setGeometry(QtCore.QRect(650, 115, 113, 32))
        self.Browse1.setObjectName("Browse1")
        self.AfficheFilm1 = QtWidgets.QLabel(PageKevinBacon)
        self.AfficheFilm1.setGeometry(QtCore.QRect(150, 230, 161, 221))
        self.AfficheFilm1.setText("")
        self.AfficheFilm1.setScaledContents(True)
        self.AfficheFilm1.setObjectName("AfficheFilm1")
        self.Browse2 = QtWidgets.QPushButton(PageKevinBacon)
        self.Browse2.setGeometry(QtCore.QRect(650, 145, 113, 32))
        self.Browse2.setObjectName("Browse2")
        self.Search = QtWidgets.QPushButton(PageKevinBacon)
        self.Search.setGeometry(QtCore.QRect(23, 180, 113, 32))
        self.Search.setObjectName("Search")
        self.ReturnButton = QtWidgets.QPushButton(PageKevinBacon)
        self.ReturnButton.setGeometry(QtCore.QRect(23, 210, 113, 32))
        self.ReturnButton.setObjectName("ReturnButton")

        self.retranslateUi(PageKevinBacon)
        QtCore.QMetaObject.connectSlotsByName(PageKevinBacon)

    def retranslateUi(self, PageKevinBacon):
        _translate = QtCore.QCoreApplication.translate
        PageKevinBacon.setWindowTitle(_translate("PageKevinBacon", "Form"))
        self.Collection.setText(_translate("PageKevinBacon", "KEVIN BACON"))
        self.JolisPoints.setText(_translate("PageKevinBacon", "..."))
        self.Browse1.setText(_translate("PageKevinBacon", "Help"))
        self.Browse2.setText(_translate("PageKevinBacon", "Help"))
        self.Search.setText(_translate("PageKevinBacon", "Search"))
        self.ReturnButton.setText(_translate("PageKevinBacon", "Return"))

