# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PageKevinBacon.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PageKevinBacon(object):
    def setupUi(self, PageKevinBacon):
        PageKevinBacon.setObjectName("PageKevinBacon")
        PageKevinBacon.resize(779, 489)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        PageKevinBacon.setPalette(palette)
        self.Collection = QtWidgets.QLabel(PageKevinBacon)
        self.Collection.setGeometry(QtCore.QRect(-20, -10, 801, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(234, 144, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 144, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Collection.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.Collection.setFont(font)
        self.Collection.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Collection.setObjectName("Collection")
        self.lineEdit = QtWidgets.QLineEdit(PageKevinBacon)
        self.lineEdit.setGeometry(QtCore.QRect(30, 120, 601, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(PageKevinBacon)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 150, 601, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(PageKevinBacon)
        self.pushButton.setGeometry(QtCore.QRect(640, 115, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(PageKevinBacon)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 145, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.TableFilmsCorrespondants = QTableWidget2(PageKevinBacon)
        self.TableFilmsCorrespondants.setGeometry(QtCore.QRect(30, 200, 721, 261))
        self.TableFilmsCorrespondants.setShowGrid(False)
        self.TableFilmsCorrespondants.setCornerButtonEnabled(False)
        self.TableFilmsCorrespondants.setRowCount(10)
        self.TableFilmsCorrespondants.setColumnCount(1)
        self.TableFilmsCorrespondants.setObjectName("TableFilmsCorrespondants")
        self.TableFilmsCorrespondants.horizontalHeader().setVisible(False)
        self.TableFilmsCorrespondants.horizontalHeader().setDefaultSectionSize(271)
        self.TableFilmsCorrespondants.verticalHeader().setVisible(False)
        self.TableFilmsCorrespondants.verticalHeader().setDefaultSectionSize(20)

        self.retranslateUi(PageKevinBacon)
        QtCore.QMetaObject.connectSlotsByName(PageKevinBacon)

    def retranslateUi(self, PageKevinBacon):
        _translate = QtCore.QCoreApplication.translate
        PageKevinBacon.setWindowTitle(_translate("PageKevinBacon", "Form"))
        self.Collection.setText(_translate("PageKevinBacon", "KEVIN BACON"))
        self.pushButton.setText(_translate("PageKevinBacon", "Browse"))
        self.pushButton_2.setText(_translate("PageKevinBacon", "Browse"))

from QTableWidget2 import QTableWidget2
