# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PageLiensFilms.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PageLiensFilms(object):
    def setupUi(self, PageLiensFilms):
        PageLiensFilms.setObjectName("PageLiensFilms")
        PageLiensFilms.resize(800, 500)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        PageLiensFilms.setPalette(palette)
        self.TitrePage = QtWidgets.QLabel(PageLiensFilms)
        self.TitrePage.setGeometry(QtCore.QRect(0, -10, 801, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(234, 144, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 144, 221))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 243, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.TitrePage.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Haettenschweiler")
        font.setPointSize(100)
        font.setBold(True)
        font.setWeight(75)
        self.TitrePage.setFont(font)
        self.TitrePage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TitrePage.setObjectName("TitrePage")
        self.Affiche1 = QtWidgets.QLabel(PageLiensFilms)
        self.Affiche1.setGeometry(QtCore.QRect(140, 110, 211, 311))
        self.Affiche1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Affiche1.setText("")
        self.Affiche1.setPixmap(QtGui.QPixmap("Images/classic-poster1-movie.jpg"))
        self.Affiche1.setScaledContents(True)
        self.Affiche1.setObjectName("Affiche1")
        self.Affiche2 = QtWidgets.QLabel(PageLiensFilms)
        self.Affiche2.setGeometry(QtCore.QRect(450, 110, 211, 311))
        self.Affiche2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Affiche2.setText("")
        self.Affiche2.setPixmap(QtGui.QPixmap("Images/classic-poster1-movie.jpg"))
        self.Affiche2.setScaledContents(True)
        self.Affiche2.setObjectName("Affiche2")
        self.Titre1 = QtWidgets.QLabel(PageLiensFilms)
        self.Titre1.setGeometry(QtCore.QRect(90, 430, 311, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(247, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Titre1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Titre1.setFont(font)
        self.Titre1.setAlignment(QtCore.Qt.AlignCenter)
        self.Titre1.setObjectName("Titre1")
        self.Titre2 = QtWidgets.QLabel(PageLiensFilms)
        self.Titre2.setGeometry(QtCore.QRect(400, 430, 311, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(247, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 253, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Titre2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Titre2.setFont(font)
        self.Titre2.setAlignment(QtCore.Qt.AlignCenter)
        self.Titre2.setObjectName("Titre2")
        self.JolisPoints = QtWidgets.QLabel(PageLiensFilms)
        self.JolisPoints.setGeometry(QtCore.QRect(370, 220, 61, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.JolisPoints.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(78)
        self.JolisPoints.setFont(font)
        self.JolisPoints.setObjectName("JolisPoints")
        self.PointDroit = QtWidgets.QLabel(PageLiensFilms)
        self.PointDroit.setGeometry(QtCore.QRect(680, -10, 91, 311))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.PointDroit.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(400)
        self.PointDroit.setFont(font)
        self.PointDroit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PointDroit.setObjectName("PointDroit")
        self.PointGauche = QtWidgets.QLabel(PageLiensFilms)
        self.PointGauche.setEnabled(False)
        self.PointGauche.setGeometry(QtCore.QRect(20, -10, 91, 311))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.PointGauche.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(400)
        self.PointGauche.setFont(font)
        self.PointGauche.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PointGauche.setObjectName("PointGauche")
        self.PointDroitFleche = QLabel3(PageLiensFilms)
        self.PointDroitFleche.setGeometry(QtCore.QRect(718, 253, 31, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.PointDroitFleche.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.PointDroitFleche.setFont(font)
        self.PointDroitFleche.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PointDroitFleche.setObjectName("PointDroitFleche")
        self.PointGaucheFleche = QLabel3(PageLiensFilms)
        self.PointGaucheFleche.setGeometry(QtCore.QRect(53, 253, 31, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 47, 47))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.PointGaucheFleche.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.PointGaucheFleche.setFont(font)
        self.PointGaucheFleche.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PointGaucheFleche.setObjectName("PointGaucheFleche")
        self.Cadre2 = QLabel2(PageLiensFilms)
        self.Cadre2.setGeometry(QtCore.QRect(450, 110, 211, 311))
        self.Cadre2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cadre2.setText("")
        self.Cadre2.setScaledContents(True)
        self.Cadre2.setObjectName("Cadre2")
        self.Cadre1 = QLabel2(PageLiensFilms)
        self.Cadre1.setGeometry(QtCore.QRect(140, 110, 211, 311))
        self.Cadre1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Cadre1.setText("")
        self.Cadre1.setScaledContents(True)
        self.Cadre1.setObjectName("Cadre1")

        self.retranslateUi(PageLiensFilms)
        QtCore.QMetaObject.connectSlotsByName(PageLiensFilms)

    def retranslateUi(self, PageLiensFilms):
        _translate = QtCore.QCoreApplication.translate
        PageLiensFilms.setWindowTitle(_translate("PageLiensFilms", "Form"))
        self.TitrePage.setText(_translate("PageLiensFilms", "AND THE LINKS ARE..."))
        self.Titre1.setText(_translate("PageLiensFilms", "Titre1"))
        self.Titre2.setText(_translate("PageLiensFilms", "Titre2"))
        self.JolisPoints.setText(_translate("PageLiensFilms", "..."))
        self.PointDroit.setText(_translate("PageLiensFilms", "."))
        self.PointGauche.setText(_translate("PageLiensFilms", "."))
        self.PointDroitFleche.setText(_translate("PageLiensFilms", ">"))
        self.PointGaucheFleche.setText(_translate("PageLiensFilms", "<"))

from QLabel2 import QLabel2
from QLabel3 import QLabel3
